# **<span style="color:skyblue;">1. What is a Python library? Why do we use Python libraries?</span>**

A collection of prewritten code that we can use to perform specific tasks such as mathematical operations, data manipulation, interacting with APIs without writing code from scratch. They are `modules containing functions, classes, methods, and variables, packaged tools that are easily reused`.

It is used for several reasons:
- **<span style="color:green;">Efficiency</span>**
- **<span style="color:green;">Code Reusability</span>**
- **<span style="color:green;">Complexity Management</span>**
- **<span style="color:green;">Reliability</span>**

# **<span style="color:#ff0000;">2. What is the difference between NumPy array and List?</span>**

| **Feature**               | **NumPy Array**                                           | **Python List**                                          |
|---------------------------|-----------------------------------------------------------|----------------------------------------------------------|
| **Performance**           | Faster and more memory-efficient for large datasets because they are implemented in C and use contiguous memory blocks. | Slower and less memory-efficient because they are more flexible and can store different data types.                     |
| **Data Type Consistency** | Homogeneous (same data type for all elements)             | Heterogeneous (can store different data types)            |
| **Functionality**         | Advanced mathematical operations, broadcasting, vectorization | General-purpose methods, lacks advanced numerical capabilities |

# **<span style = "color:rgb(125,78,89);">3. Find the shape, size and dimension of the following array? </span>**
# 4. Write python code to access the first row of the following array?
# 5. How do you access the element at the third row and fourth column from the given numpy array?
# 6. Write code to extract all odd-indexed elements from the given numpy array?
# 9. Write code to increase the dimension of the following array?
# 10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

9, 10, 11, 12]]

In [56]:
import numpy as np
l =  [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
arr = np.array(l)
print(f"""
Shape: {arr.shape}
Size: {arr.size}
Dimension: {arr.ndim} 
First Row: {arr[0]}
Third Row and Forth Column: {arr[2,3]}
All Odd Indexed Element (Assuming Rows are Indexing and columns are features) : {arr[::2]} 
Increase Dimension by 1D by Row : {np.expand_dims(arr,axis = 0)}
Increase Dimension by 1D by Column : {np.expand_dims(arr,axis = 1)}
Transpose: {arr.T}

""")


Shape: (3, 4)
Size: 12
Dimension: 2 
First Row: [1 2 3 4]
Third Row and Forth Column: 12
All Odd Indexed Element (Assuming Rows are Indexing and columns are features) : [[ 1  2  3  4]
 [ 9 10 11 12]] 
Increase Dimension by 1D by Row : [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Increase Dimension by 1D by Column : [[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
Transpose: [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]




# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [65]:
import random
np.random.rand(3,3)

array([[0.66862078, 0.2157137 , 0.74504698],
       [0.75824598, 0.36606565, 0.16011677],
       [0.81533577, 0.70704713, 0.77720769]])

# 8. Describe the difference between np.random.rand and np.random.randn

- `np.random.rand` : Random numbers in a uniform distribution between 0 and 1.
- `np.random.randn` : Random numbers from a standard normal distribution with a mean of 0 and a standard deviation of 1.

# 11. Consider the following matrix:

Matrix A:  [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1
-  Index wise multiplication
- Matrix multiplication
- Add both the matrix
- Subtract matrix B from A
- Divide Matrix B by A

In [71]:
A = arr.copy()
B = arr.copy()
print(f"""
A: {A}
B: {B}
""")


A: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
B: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]



In [85]:
print(f"""
Index wise multiplication: {A*B}
Matrix Multiplication: {A @ B.T}   # Because size  A = 3,4 & B = 3,4 
Matrix Multiplication: {np.dot(A,B.T)}
Add both Matrix: {A+B}
Subtract Matrix B from A: {B-A}
Divide Matrix B by A:  {B/A}
""")


Index wise multiplication: [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix Multiplication: [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]   # Because size  A = 3,4 & B = 3,4 
Matrix Multiplication: [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Add both Matrix: [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtract Matrix B from A: [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Divide Matrix B by A:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



# 12.  Which function in Numpy can be used to swap the byte order of an array?

In [93]:
A.byteswap()

array([[ 16777216,  33554432,  50331648,  67108864],
       [ 83886080, 100663296, 117440512, 134217728],
       [150994944, 167772160, 184549376, 201326592]])

# 13.  What is the significance of the np.linalg.inv function?
The `np.linalg.inv()` function in NumPy is used to compute the multiplicative inverse of a square matrix. Understanding this function and its significance is crucial in many fields, especially in linear algebra, data science, and various numerical applications.

In [118]:
a = np.random.randint(1,10, size = (3,3))
print(f"""Multiplicative inverse of 
{a}   \n   ||\n{np.linalg.inv(a)}""")

Multiplicative inverse of 
[[2 9 8]
 [3 1 3]
 [2 8 2]]   
   ||
[[-0.16666667  0.34848485  0.14393939]
 [ 0.         -0.09090909  0.13636364]
 [ 0.16666667  0.01515152 -0.18939394]]


# 14. What does the np.reshape function do, and how is it used?
a.reshape(shape, order='C')

Returns an array containing the same data with a new shape.
# 15. What is broadcasting in Numpy
allows for element-wise operations between arrays of different shapes. Instead of requiring arrays to be of the same shape, broadcasting automatically expands the smaller array across the larger array so that they have compatible shapes for operations like addition, multiplication, etc.

Key Concepts of Broadcasting
Shape Compatibility:

Two arrays are compatible for broadcasting if, when aligned from the trailing dimensions, all corresponding dimensions either:
- Are equal, or
- One of them is 1.

Broadcasting Rules:

              Rule 1: If the arrays do not have the same number of dimensions, prepend dimensions of size 1 to the smaller array.

              Rule 2: The size in each dimension must be the same, or one of the sizes is 1.

In [123]:
import numpy as np

# Array 'a' is of shape (3,)
a = np.array([1, 2, 3])

# Array 'b' is of shape (3, 1)
b = np.array([[1], [2], [3]])

# Broadcasting 'a' to the shape of 'b' for element-wise addition
c = a + b
print(c)


[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [125]:
import numpy as np

# Array 'a' is of shape (3,)
a = np.array([1, 2, 3])

# Scalar value 'b'
b = 2

# Broadcasting the scalar across the array for multiplication
c = a * b
print(c)


[2 4 6]


The `ndarray.byteswap()` method in NumPy is used to swap the byte order of elements within an array, effectively toggling between different endianness representations (big-endian and little-endian). Endianness refers to the order in which bytes are arranged within a data type. In a big-endian system, the most significant byte (the "big end") is stored at the smallest memory address, while in a little-endian system, the least significant byte is stored first.

### Why is `byteswap()` Important?
Endianness is significant in scenarios where data is transferred between different systems that may have different byte orders. For example, data might be written on a system that uses big-endian format and then read on a system that uses little-endian format. Without converting between these formats, the data would be interpreted incorrectly, leading to potentially significant errors.

### Application in Data Science
In Data Science, `byteswap()` can be crucial when working with binary data formats or when performing low-level data manipulations, such as:
1. **Cross-System Compatibility**: When processing datasets that were generated on different architectures (e.g., between big-endian and little-endian systems), `byteswap()` helps ensure that data is correctly interpreted.
2. **Data Integration**: When merging data from different sources or systems, it's important to handle endianness properly to avoid corrupted or misinterpreted data.
3. **Machine Learning Preprocessing**: When deploying models across various platforms, ensuring that the data fed to the model is in the correct byte order can prevent runtime errors or incorrect predictions.

### Application in Software Development
In software development, particularly in system programming or network programming, `byteswap()` is used in:
1. **Network Protocols**: Many network protocols specify the byte order (often big-endian, also known as "network byte order"). Developers must ensure that data sent over the network is in the correct byte order, and `byteswap()` is a convenient tool for this.
2. **File I/O**: When reading or writing binary files that are meant to be cross-platform, developers need to ensure that the byte order is consistent. `byteswap()` allows toggling the byte order to match the required format.
3. **Hardware Interfacing**: Interfacing with hardware devices that have specific byte order requirements often necessitates converting data to the appropriate format using `byteswap()`.

### Example Scenario
Imagine you're working on a cross-platform machine learning project where the training data is stored in a binary format. The data was generated on a big-endian system but needs to be processed on a little-endian system. Using `byteswap()` allows you to convert the data into the correct byte order before feeding it into your machine learning pipeline.

5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?


8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?

 

9. Write co^e to increase the ^imension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


11. Consi^er the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1
,+ I(dex wiLe multiplicatio'
]+ Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om 
+ Diide Matix B by A


12.  Which function in Numpy can be use^ to swap the byte or^er of an array?

13.  What is the significance of the np.linalg.inv function?

14. What ^oes the np.reshape function ^o, an^ how is it use^?

15. What is broa^casting in Numpy